// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoryGame.DAL;

#nullable disable

namespace StoryGame.Migrations
{
    [DbContext(typeof(StoryDbContext))]
    [Migration("20251016175926_addedFirstScene")]
    partial class addedFirstScene
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("StoryGame.Models.Choice", b =>
                {
                    b.Property<int>("ChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NextSceneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThisSceneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChoiceId");

                    b.HasIndex("NextSceneId");

                    b.HasIndex("ThisSceneId");

                    b.ToTable("Choices");
                });

            modelBuilder.Entity("StoryGame.Models.Scene", b =>
                {
                    b.Property<int>("SceneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinalScene")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFirstScene")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SceneId");

                    b.HasIndex("StoryId");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("StoryGame.Models.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StoryId");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("StoryGame.Models.Choice", b =>
                {
                    b.HasOne("StoryGame.Models.Scene", "NextScene")
                        .WithMany()
                        .HasForeignKey("NextSceneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StoryGame.Models.Scene", "ThisScene")
                        .WithMany("ChoiceList")
                        .HasForeignKey("ThisSceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NextScene");

                    b.Navigation("ThisScene");
                });

            modelBuilder.Entity("StoryGame.Models.Scene", b =>
                {
                    b.HasOne("StoryGame.Models.Story", "Story")
                        .WithMany("ScenesList")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("StoryGame.Models.Scene", b =>
                {
                    b.Navigation("ChoiceList");
                });

            modelBuilder.Entity("StoryGame.Models.Story", b =>
                {
                    b.Navigation("ScenesList");
                });
#pragma warning restore 612, 618
        }
    }
}
